POST  http://localhost:3000/api/pages
Content-Type: application/json

{
    "title": "page1",
    "authorId":1,
    "publicationDate": "2023-06-20",
    "blocks": [
      {
        "type": "header",
        "content": "header1",
        "position":1
      },
      {
        "type": "image",
        "content": "img/image1.png",
        "position":2
      }
    ]
  }

###

GET  http://localhost:3000/api/pages/frontoffice